"""Candidate findings for the Day 2 post, every number computed from the same
data and functions the viz uses. Writes analysis/candidate_findings.md.

Comparisons across years use harmonized occupation groups (as in the viz's
change-over-time view) and only places/years that pass the history tests.
"""
import os, sys
import numpy as np, pandas as pd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lorenz import gini, usable, harmonize
from geo import area_key

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INT = os.path.join(ROOT, "data/interim")
HHA = "31-1120"      # Home Health and Personal Care Aides; before 2019 = 31-1011 + 39-9021

cmap = pd.read_parquet(os.path.join(INT, "soc_harmonized_map.parquet"))
titles = cmap.drop_duplicates("hgroup").set_index("hgroup").hgroup_title
H, RAW = {}, {}
for y in (2013, 2016, 2019, 2022, 2025):
    d = pd.read_parquet(os.path.join(INT, f"oews_{y}.parquet")); d["akey"] = area_key(d.area); RAW[y] = d
    h = harmonize(d, cmap[["year", "occ_code", "hgroup"]].drop_duplicates()); h["akey"] = area_key(h.area); H[y] = h
# Annual jobs in the aide group for every area, 2013-2025, to catch one-year jumps that
# signal a change in what BLS counts rather than real growth (each May estimate pools
# three years of surveys, so real growth phases in).
ANN = {}
for y in range(2013, 2026):
    d = pd.read_parquet(os.path.join(INT, f"oews_{y}.parquet"))
    d = d[d.o_group.isin(["detailed", "detail"]) & d.tot_emp.notna()]          # job counts, even where BLS withheld the wage
    d = d.merge(cmap[cmap.year == y][["occ_code", "hgroup"]], on="occ_code")
    d = d[d.hgroup == HHA]; ANN[y] = d.assign(akey=area_key(d.area)).groupby("akey").tot_emp.sum()
ANN = pd.DataFrame(ANN)


PRE2019 = ["31-1011", "39-9021"]


def complete_2016(akey):
    """Both pre-2019 codes published (jobs and wage) for this area in May 2016, so the 2016 group total is whole."""
    d = RAW[2016]; d = d[(d.akey == akey) & d.occ_code.isin(PRE2019)]
    return len(d) == 2 and d.tot_emp.notna().all() and d.a_mean.notna().all()


def step_years(akey, y0=2013, min_jobs=1000, jump=0.5):
    """Years where aide jobs rose more than 50% (and 1,000 jobs) over the year before."""
    if akey not in ANN.index: return []
    s = ANN.loc[akey]
    return [y for y in range(y0 + 1, 2026) if pd.notna(s.get(y)) and pd.notna(s.get(y - 1)) and s[y] - s[y - 1] > min_jobs and s[y] / s[y - 1] - 1 > jump]


tests = pd.read_csv(os.path.join(INT, "history_tests.csv"), dtype={"akey": str, "start_area": str})
metrics = pd.read_parquet(os.path.join(INT, "area_metrics.parquet")); metrics["akey"] = area_key(metrics.area)
m25 = metrics[metrics.year == 2025].set_index("akey")
name = m25.area_title
inc = pd.read_csv(os.path.join(INT, "bea_income_by_area.csv"), dtype={"area": str})
out = []
w = out.append
pct = lambda v, d=1: f"{v*100:.{d}f}%"
usd = lambda v: f"${v:,.0f}"


def curve(h):
    h = h.sort_values("a_mean", kind="stable")
    x = h.tot_emp.cumsum() / h.tot_emp.sum(); y = h.wages.cumsum() / h.wages.sum()
    return h.assign(x=x.values, y=y.values, job_share=(h.tot_emp / h.tot_emp.sum()).values, wage_share=(h.wages / h.wages.sum()).values)


def share_at(h, p):
    c = curve(h); return float(np.interp(p, np.r_[0, c.x], np.r_[0, c.y]))


def group_row(akey, year, start_area=None, g=HHA):
    h = H[year][H[year].akey == (start_area or akey)]
    c = curve(h); r = c[c.hgroup == g]
    if r.empty: return None
    r = r.iloc[0]
    rank = int((c.tot_emp > r.tot_emp).sum() + 1)
    return dict(jobs=r.tot_emp, share=r.job_share, wage=r.a_mean, wage_share=r.wage_share, x=r.x, rank=rank, n=len(c))


def published(akey, year, codes):
    d = RAW[year]; d = d[(d.akey == akey) & d.occ_code.isin(codes)]
    return {c: ("published" if pd.notna(r.tot_emp) and pd.notna(r.a_mean) else f"not published ({r.tot_emp_flag or r.a_mean_flag})")
            for c, r in zip(d.occ_code, d.itertuples())}

w("# Candidate findings for Day 2\n")
w("Generated by `scripts/09_findings.py`. Every number is computed from the same data the viz uses. "
  "Comparisons across years use the combined occupation list and only places that pass the history tests. "
  "Gini here always means the Gini of payroll wages across occupations. Dollar figures are not adjusted for inflation.\n")

# ---------------------------------------------------------------- 1. home health aides
w("## Data issues found while building this list\n")
w("- **California counting change, May 2017.** OEWS counts of home health and personal care aides in California went from "
  f"{ANN.loc['6', 2016]:,.0f} (May 2016) to {ANN.loc['6', 2017]:,.0f} (May 2017). Each May estimate pools three years of surveys, so real growth "
  "phases in; a one-year tripling points to a change in who is counted. The UC Berkeley Labor Center (Thomason and Bernhardt, November 2017) "
  "reported 558,000 personal care and home health aides in California in 2014, 410,000 of them In-Home Supportive Services providers, while "
  f"OEWS counted {ANN.loc['6', 2014]:,.0f} that year. BLS's May 2017 occupation page has no note on it; this is our inference. "
  "Effect on the history verdicts: none. All 26 California verdicts hold with the aide group removed from both years.")
w("- **BLS file error, May 2013.** U.S. Hunters and Trappers shows exactly 99,999 jobs (not published nationally in 2012 or 2014). Treated as missing; "
  "it moved the U.S. Gini by 0.0001.\n")
w("## 1. Home health and personal care aides (requested)\n")
w("BLS merged Home Health Aides (31-1011) and Personal Care Aides (39-9021) into one code (31-1120) starting May 2019. "
  "Every year below counts both, so the comparison is the same set of jobs each year.\n")
w("| Place | Year | Jobs | Share of all jobs | Rank by jobs | Average wage | Workers up to and including this bubble |")
w("|---|---|---|---|---|---|---|")
for ak, label, years in [("99", "U.S.", (2013, 2016, 2019, 2022, 2025)), ("36", "New York State", (2013, 2016, 2019, 2022, 2025)),
                         ("35620", "New York metro", (2016, 2019, 2022, 2025))]:
    for y in years:
        sa = None
        if ak == "35620" and y != 2025:
            sa = tests[(tests.akey == ak) & (tests.start == y)].start_area.iloc[0]
        r = group_row(ak, y, sa)
        if r: w(f"| {label} | May {y} | {r['jobs']:,.0f} | {pct(r['share'])} | {r['rank']} of {r['n']} | {usd(r['wage'])} | {pct(r['x'])} |")
ny16, ny25 = group_row("35620", 2016, "35620"), group_row("35620", 2025)
w(f"\nNew York metro, May 2016 to May 2025: jobs {ny16['jobs']:,.0f} to {ny25['jobs']:,.0f} "
  f"({(ny25['jobs']/ny16['jobs']-1)*100:.0f}% more), share of all jobs {pct(ny16['share'])} to {pct(ny25['share'])}.")
w(f"Codes published for New York metro: 2016 {published('35620', 2016, ['31-1011', '39-9021'])}; 2025 {published('35620', 2025, ['31-1120'])}.")
w("New York metro jobs in this group every May, 2016 to 2025: " + ", ".join(f"{ANN.loc['35620', y]:,.0f}" for y in range(2016, 2026))
  + f". One-year jumps over 50%: {step_years('35620', 2016) or 'none'}. New York State: {step_years('36') or 'none'}.")
us_ex_ca = {y: ANN.loc['99', y] - ANN.loc['6', y] for y in (2013, 2016, 2025)}
w(f"U.S. excluding California: {us_ex_ca[2013]:,.0f} (2013), {us_ex_ca[2016]:,.0f} (2016), {us_ex_ca[2025]:,.0f} (2025). "
  "Use this, or start the U.S. comparison at May 2019 (after California's change), for any national growth claim.\n")
# where it is biggest, and where it grew most, among metros with history from 2016
rows = []
for _, t in tests[(tests.start == 2016) & (tests.area_type == 4)].iterrows():
    a, b = group_row(t.akey, 2016, t.start_area), group_row(t.akey, 2025)
    if a and b: rows.append(dict(akey=t.akey, area=name[t.akey], s16=a["share"], s25=b["share"], j16=a["jobs"], j25=b["jobs"], rank25=b["rank"],
                                 steps=step_years(t.akey, 2016), whole=complete_2016(t.start_area)))
r = pd.DataFrame(rows); r["pts"] = r.s25 - r.s16
flagged = r[r.steps.str.len() > 0]
w(f"Metros with a one-year jump over 50% in this group between 2016 and 2025 (possible counting change, left out of the rankings below): "
  f"{len(flagged)}, of which {flagged.area.str.endswith(', CA').sum()} in California.\n")
w(f"Metros where May 2016 is missing one of the two codes (so the 2016 total is incomplete, also left out): {(~r.whole).sum()}.\n")
r = r[(r.steps.str.len() == 0) & r.whole]
w(f"Across {len(r)} metros with comparable data, the group's share of jobs rose in {(r.pts > 0).sum()} and fell in {(r.pts < 0).sum()}. "
  f"It is the single largest occupation by jobs in {(r.rank25 == 1).sum()} of them in May 2025.\n")
w("Largest share of jobs, May 2025 (metros with comparable data):\n")
w("| Metro | 2016 share | 2025 share | Jobs 2016 | Jobs 2025 |"); w("|---|---|---|---|---|")
for _, x in r.sort_values("s25", ascending=False).head(10).iterrows():
    w(f"| {x.area} | {pct(x.s16)} | {pct(x.s25)} | {x.j16:,.0f} | {x.j25:,.0f} |")
w("\nLargest rise in share of jobs, 2016 to 2025 (percentage points):\n")
w("| Metro | 2016 share | 2025 share | Change |"); w("|---|---|---|---|")
for _, x in r.sort_values("pts", ascending=False).head(10).iterrows():
    w(f"| {x.area} | {pct(x.s16)} | {pct(x.s25)} | {x.pts*100:+.1f} pts |")

# ---------------------------------------------------------------- 2. U.S. gap narrowed
us = tests[tests.akey == "99"].set_index("start")
w("\n## 2. The U.S. gap between occupations narrowed\n")
h13, h25 = H[2013][H[2013].akey == "99"], H[2025][H[2025].akey == "99"]
w(f"U.S. Gini of payroll wages across occupations: {us.loc[2013, 'g0']:.4f} (May 2013) to {us.loc[2013, 'g1']:.4f} (May 2025), "
  f"change {us.loc[2013, 'ch_harm']:+.4f}; noise range {2*us.loc[2013,'sd']:.4f}. Verdict: {us.loc[2013, 'verdict']}.")
w(f"Share of payroll wages earned by the lowest-paid half of workers: {pct(share_at(h13, .5))} (2013) to {pct(share_at(h25, .5))} (2025). "
  f"Top-paid 10%: {pct(1-share_at(h13, .9))} to {pct(1-share_at(h25, .9))}.")
w("Limit to state alongside it: payroll wages only; says nothing about business or investment income.\n")

# ---------------------------------------------------------------- 3. states
w("## 3. States since 2013\n")
s = tests[(tests.start == 2013) & (tests.area_type == 2)].copy()
v = s.verdict.value_counts()
w(f"{v.get('clear drop', 0)} of 51 narrowed clearly, {v.get('clear rise', 0)} widened clearly, {v.get('no clear change', 0)} no clear change "
  f"({', '.join(s[s.verdict == 'no clear change'].area_title)}).\n")
w("| Largest narrowing | 2013 | 2025 | Change |"); w("|---|---|---|---|")
for _, x in s.sort_values("ch_harm").head(5).iterrows(): w(f"| {x.area_title} | {x.g0:.4f} | {x.g1:.4f} | {x.ch_harm:+.4f} |")
w("\n| Smallest narrowing | 2013 | 2025 | Change | Verdict |"); w("|---|---|---|---|---|")
for _, x in s.sort_values("ch_harm", ascending=False).head(5).iterrows(): w(f"| {x.area_title} | {x.g0:.4f} | {x.g1:.4f} | {x.ch_harm:+.4f} | {x.verdict} |")

# ---------------------------------------------------------------- 4. metros since 2016
w("\n## 4. Metros since 2016\n")
mt = tests[(tests.start == 2016) & (tests.area_type == 4)]
v = mt.verdict.value_counts()
w(f"{len(mt)} metros with comparable data: {v.get('clear drop', 0)} narrowed clearly, {v.get('clear rise', 0)} widened clearly "
  f"({', '.join(mt[mt.verdict == 'clear rise'].area_title) or 'none'}), {v.get('no clear change', 0)} no clear change.\n")
w("| Largest narrowing | 2016 | 2025 | Change |"); w("|---|---|---|---|")
for _, x in mt.sort_values("ch_harm").head(8).iterrows(): w(f"| {x.area_title} | {x.g0:.4f} | {x.g1:.4f} | {x.ch_harm:+.4f} |")

# ---------------------------------------------------------------- 5. recent years mixed
w("\n## 5. Since 2022 the picture is mixed\n")
for t, lab in ((2, "states"), (4, "metros")):
    g = tests[(tests.start == 2022) & (tests.area_type == t)]; v = g.verdict.value_counts()
    w(f"- {lab}, May 2022 to May 2025: {v.get('clear drop', 0)} narrowed, {v.get('clear rise', 0)} widened, {v.get('no clear change', 0)} no clear change.")
w(f"- U.S.: {us.loc[2022, 'ch_harm']:+.4f} ({us.loc[2022, 'verdict']}).\n")
g = tests[(tests.start == 2022) & (tests.area_type == 2) & (tests.verdict == "clear rise")].sort_values("ch_harm", ascending=False)
w("States that widened clearly since 2022: " + ", ".join(f"{x.area_title} ({x.ch_harm:+.4f})" for _, x in g.iterrows()) + ".\n")

# ---------------------------------------------------------------- 6. most / least equal, May 2025
w("## 6. Most and least equal, May 2025 (native detail, as in the May 2025 view)\n")
for t, lab in ((2, "States"), (4, "Metros")):
    g = m25[m25.area_type == t].sort_values("gini")
    if t == 4: g = g[~g.area_title.str.contains(", PR")]
    w(f"- {lab}, least equal: " + "; ".join(f"{x.area_title} {x.gini:.4f}" for _, x in g.tail(5).iloc[::-1].iterrows()))
    w(f"- {lab}, most equal: " + "; ".join(f"{x.area_title} {x.gini:.4f}" for _, x in g.head(5).iterrows()))
w("  (Puerto Rico metros excluded from the metro list; they are the most equal but have much lower wages overall.)\n")

# ---------------------------------------------------------------- 7. major groups
w("## 7. Which groups take more of the wages than their share of jobs (U.S., May 2025)\n")
d = usable(RAW[2025][RAW[2025].area_type == 1]).assign(major=lambda x: x.occ_code.str[:2])
d["wages"] = d.tot_emp * d.a_mean
maj = RAW[2025][RAW[2025].o_group == "major"].drop_duplicates("occ_code").set_index(RAW[2025][RAW[2025].o_group == "major"].drop_duplicates("occ_code").occ_code.str[:2]).occ_title
gsum = d.groupby("major")[["tot_emp", "wages"]].sum(); gsum = gsum.assign(js=gsum.tot_emp / gsum.tot_emp.sum(), ws=gsum.wages / gsum.wages.sum())
gsum["ratio"] = gsum.ws / gsum.js
w("| Major group | Share of jobs | Share of wages | Wages per job vs. average |"); w("|---|---|---|---|")
for m, x in gsum.sort_values("ratio", ascending=False).iterrows():
    w(f"| {maj[m]} | {pct(x.js)} | {pct(x.ws)} | {(x.ratio-1)*100:+.0f}% |")

# ---------------------------------------------------------------- 8. BEA: what the curve can't see
w("\n## 8. What the curve can't see (BEA personal income by source, 2013 to 2024)\n")
b = inc[inc.complete].copy(); b["not_on"] = 1 - b.wages / b.personal_income; b["dir"] = b.dividends_interest_rent / b.personal_income
bw = b.pivot_table(index="area", columns="year", values=["not_on", "dir"])
usb = bw.loc["99"]
w(f"U.S.: not on the curve {pct(usb[('not_on', 2013)])} (2013) to {pct(usb[('not_on', 2024)])} (2024); "
  f"dividends, interest and rent {pct(usb[('dir', 2013)])} to {pct(usb[('dir', 2024)])}.")
for t, lab in ((2, "states"), (4, "metros")):
    ks = [k for k in m25.index[m25.area_type == t] if k in bw.index and not np.isnan(bw.loc[k, ('not_on', 2013)])]
    x = bw.loc[ks]
    grew = (x[('not_on', 2024)] > x[('not_on', 2013)]).sum(); dg = (x[('dir', 2024)] > x[('dir', 2013)]).sum()
    w(f"- {lab} ({len(ks)} with both years): not-on-the-curve share grew in {grew}, shrank in {len(ks)-grew}; "
      f"dividends, interest and rent share rose in {dg} of {len(ks)}.")
w("Limit: shows where income comes from, not who receives it; capital gains are not in personal income.\n")

# ---------------------------------------------------------------- 9. bottom half
w("## 9. Where the lowest-paid half gets the smallest slice (metros, May 2025)\n")
rows = []
for ak in m25.index[m25.area_type == 4]:
    u = usable(RAW[2025][RAW[2025].akey == ak])
    if len(u) == 0 or ", PR" in name[ak]: continue
    h = u.assign(wages=u.tot_emp * u.a_mean, hgroup=u.occ_code)
    rows.append((name[ak], share_at(h, .5), 1 - share_at(h, .9)))
bh = pd.DataFrame(rows, columns=["area", "bottom_half", "top10"]).sort_values("bottom_half")
w("| Metro | Lowest-paid half's share | Top-paid 10%'s share |"); w("|---|---|---|")
for _, x in bh.head(6).iterrows(): w(f"| {x.area} | {pct(x.bottom_half)} | {pct(x.top10)} |")
w(f"\nFor reference, U.S.: lowest-paid half {pct(share_at(h25.assign(), .5))}.\n")

open(os.path.join(ROOT, "analysis/candidate_findings.md"), "w").write("\n".join(out) + "\n")
print("\n".join(out))
